---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Understanding tags"
      solveButton: false
    - name: module-02
      label: "Filter instances based on tags"
      solveButton: false
    - name: module-03
      label: "Creating a workflow"
      solveButton: false


tabs:
  - name: Ansible Automation Platform
    url: https://control-${guid}.${domain}/
  # - name: gitea
  #   url: https://gitea-${guid}.${domain}/
  # - name: VS Ccode
  #   url: https://vscode-${guid}.${domain}
  #   external: false
  # - name: "TERMINAL"
  #   url: /wetty_control
  - name: Cloud (AWS)
    url: /cloud
